apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: exporter-monitor
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: exporter-config
    namespace: ${APP_NAMESPACE}
  data:
    SERVER_PORT: '8080'
    LOG_LEVEL: info
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: exporter-monitoring-config
    namespace: ${APP_NAMESPACE}
  data:
    example.conf: |
      environment=example
      ns-selector=app=example
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: application-exporter-monitoring
    namespace: ${APP_NAMESPACE}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: application-exporter-monitoring
    template:
      metadata:
        labels:
          app: application-exporter-monitoring
      spec:
        serviceAccountName: application-exporter
        containers:
          - image: ${APP_IMAGE}
            name: application-exporter-monitoring
            imagePullPolicy: Always
            env:
            - name: RUN_MODE
              value: monitoring
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: SERVER_PORT
                  name: exporter-config
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: LOG_LEVEL
                  name: exporter-config
            args:
              - '--with-resources'
            volumeMounts:
            - name: config-volume
              mountPath: /etc/config
        volumes:
          - name: config-volume
            configMap:
              name: exporter-monitoring-config
- kind: Service
  apiVersion: v1
  metadata:
    name: application-exporter-monitoring
    namespace: ${APP_NAMESPACE}
  spec:
    ports:
      - name: http
        protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      app: application-exporter-monitoring
    type: ClusterIP
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      k8s-app: application-exporter-monitoring
    name: application-exporter
    namespace: ${APP_NAMESPACE}
  spec:
    endpoints:
    - interval: 5m
      path: /metrics
      port: http
      scheme: http
    selector:
      matchLabels:
        app: application-exporter-monitoring
parameters:
- description: App namespace
  from: '[A-Z0-9]{8}'
  generate: expression
  name: APP_NAMESPACE
- description: App image, e.g. 'quay.io/dmartino/application-exporter:0.1.1' or 'image-registry.openshift-image-registry.svc:5000/NS/application-exporter:latest'
  from: '[A-Z0-9]{8}'
  generate: expression
  name: APP_IMAGE
labels:
  app: application-exporter-monitoring