apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: exporter-rbac
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: application-exporter
    namespace: ${APP_NAMESPACE}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: application-exporter
  rules:
    - apiGroups:
      - '*'
      resources:
      - '*'
      verbs:
      - get
      - list
- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: application-exporter-roles
  subjects:
    - kind: ServiceAccount
      name: application-exporter
      namespace: ${APP_NAMESPACE}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: application-exporter
parameters:
- description: App namespace
  from: '[A-Z0-9]{8}'
  generate: expression
  name: APP_NAMESPACE
labels:
  app: application-exporter