apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: exporter-monitor
objects:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    labels:
      k8s-app: application-exporter
    name: application-exporter
    namespace: ${APP_NAMESPACE}
  spec:
    endpoints:
    - interval: 5m
      path: /metrics
      port: http
      scheme: http
    selector:
      matchLabels:
        app: application-exporter
parameters:
- description: App namespace
  from: '[A-Z0-9]{8}'
  generate: expression
  name: APP_NAMESPACE
labels:
  app: application-exporter