name: Go

on:
  release:
    branches: [ "main" ]
    types: [published]
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build binaries
      run: |
        BUILD_VERSION=${{  github.ref_name }}
        echo Build version is: ${BUILD_VERSION}
        mkdir bin
        #GOOS=windows GOARCH=386 go build -o bin/inventory-exporter-win-386.exe -ldflags "-X main.BuildVersion=${BUILD_VERSION}" main.go
        #GOOS=windows GOARCH=amd64 go build -o bin/inventory-exporter-win-amd64.exe -ldflags "-X main.BuildVersion=${BUILD_VERSION}" main.go
        GOOS=darwin GOARCH=amd64 go build -o bin/inventory-exporter-darwin-amd64 -ldflags "-X main.BuildVersion=${BUILD_VERSION}" main.go
        #GOOS=darwin GOARCH=arm64 go build -o bin/inventory-exporter-darwin-arm64 -ldflags "-X main.BuildVersion=${BUILD_VERSION}" main.go
    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with: 
        name: binaries
        path: bin
